// <auto-generated />
using System;
using Api.Domains.OrderProcessing;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Api.Migrations.OrderProcessingDb
{
    [DbContext(typeof(OrderProcessingDbContext))]
    partial class OrderProcessingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("Api.Domains.OrderProcessing.OrderProcessingSagaState", b =>
                {
                    b.Property<Guid>("CorrelationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrentState")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastError")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastUpdated")
                        .HasColumnType("TEXT");

                    b.Property<string>("OrderCreateResponse")
                        .HasColumnType("TEXT");

                    b.Property<int>("OrderCreateRetryCount")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("OrderCreatedApiCalled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OrderProcessResponse")
                        .HasColumnType("TEXT");

                    b.Property<int>("OrderProcessRetryCount")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("OrderProcessedApiCalled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OrderShipResponse")
                        .HasColumnType("TEXT");

                    b.Property<int>("OrderShipRetryCount")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("OrderShippedApiCalled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OriginalMessage")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalMessageJson")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("CorrelationId");

                    b.ToTable("OrderProcessingSagaStates", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
